### PR TITLE
closes #166

### LINKED ISSUE #166: Add card to Account not consistent with docs or not Implemented
From the Docs:

```
stripe.Key = "sk_test_12345"

c, err := card.New(&stripe.CardParams{
  Account: "acct_1649BKGdIrMVkPmQ",
  Token: "",
}
```

This code throws an error on compile time: "unknown stripe.CardParams field 'Account' in struct literal"

There is an Account field on stripe.CardParams.Params so this compiles:
```
	cardArgs := &stripe.CardParams{
		Token: stripeToken,
	}
	cardArgs.Params.SetAccount(id)

       return card.New(cardArgs)
```

However it throws this error: "Invalid card params: either customer or recipient need to be set"

This is thrown because [card.New](https://github.com/stripe/stripe-go/blob/master/card/client.go#L43-L60) is looking explicitly for the presence of Customer or Recipient.

Looking deeper, stripe.CardParams.Params is not where we want Account as all these fields are [wrapped in metadata[...]](https://github.com/stripe/stripe-go/blob/master/params.go#L103-L117) for the request.

### PR DESCRIPTION
**Pull request by collinglass**

### CODE REVIEW

File: card.go [hunk 1]
```diff
@@ -24,8 +24,8 @@ type CardFunding string
 // For more details see https://stripe.com/docs/api#create_card and https://stripe.com/docs/api#update_card.
 type CardParams struct {
 	Params
-	Token                                         string
-	Customer, Recipient                           string
+	External_Account, Token                       string
```
Comment (brandur) [inline card.go]: I don't think we need an `External_Account` here.

File: bankaccount/client.go [hunk 2]
```diff
@@ -108,15 +107,7 @@ func Del(id string, params *stripe.BankAccountParams) (*stripe.BankAccount, erro
...
-	var err error
-
-	if len(params.Customer) > 0 {
-		err = c.B.Call("DELETE", fmt.Sprintf("/customers/%v/bank_accounts/%v", params.Customer, id), c.Key, nil, nil, ba)
-	} else if len(params.AccountID) > 0 {
-		err = c.B.Call("DELETE", fmt.Sprintf("/accounts/%v/bank_accounts/%v", params.AccountID, id), c.Key, nil, nil, ba)
-	} else {
-		err = errors.New("Invalid bank account params: either customer or AccountID need to be set")
-	}
+	err := c.B.Call("DELETE", fmt.Sprintf("/accounts/%v/bank_accounts/%v", params.AccountID, id), c.Key, nil, nil, ba)
```
Comment (brandur) [inline bankaccount/client.go]: Hm. Is there any particular reason that you collapsed these lines?

**Comment by brandur** [comment]
@collinglass Hey! I left a couple comments, but this generally looks good! Thanks for taking a stab at it.

It looks like you figured it out already, but the `Account` property under the parent `Params` struct is for authentication rather than referencing an account during an operation.

File: bankaccount/client.go (hunk 2 above)
Comment (collinglass) [inline bankaccount/client.go]: It's the only function in the client that handled Customers, I made an educated assumption. It should have been in another commit though

File: card.go (hunk 1 above)
Comment (collinglass) [inline card.go]: How do you add a debit card to an account?

Comment (brandur) [inline card.go]: Ah, I see. I think you you may have misreferenced the new field in `AppendDetails` below though. As far as I can tell, this is new used. Also, I don't think it's a string unfortunately ([create a card](https://stripe.com/docs/api/curl#create_card-source%20|%20external_account)).

File: bankaccount/client.go (hunk 2 above)
Comment (brandur) [inline bankaccount/client.go]: Cool! Let's maybe leave this one out for now. As far as I can tell it's actually the `/customers` version that's non-deprecated.

File: card.go (hunk 1 above)
Comment (collinglass) [inline card.go]: How would you handle this? From that link it tells me it's either a token or a dictionary (similar to the current implementation for customer). Second, why is ```AppendDetails``` using card instead of ```source```?

Comment (collinglass) [inline card.go]: When I remove the External_Account Param I get the follow error response:

{"type":"invalid_request_error","message":"Missing required param: external_account.","param":"external_account","request_id":"req_foo_mustache","status":400}

When I use that param, I get a successful request.

Comment (collinglass) [inline card.go]: I see my confusion :) Thanks for your patience.

**Comment by collinglass** [comment]
@brandur I made the suggested changes. Is there anything else needed on my part to get this merged?

File: card.go (hunk 1 above)
Comment (brandur) [inline card.go]: > How would you handle this? From that link it tells me it's either a token or a dictionary (similar to the current implementation for customer).

Good question. I notice that the bindings seem to have just not bothered for support on the dictionary version for customer, so it seems fine to leave it out of here for now too.

**Comment by brandur** [comment]
> @brandur I made the suggested changes. Is there anything else needed on my part to get this merged?

Sorry about the delay.

I still have some doubts around the naming of `Account` in that it seems that `ExternalAccount` might also be a good choice, but it seems that not even in the API is this anywhere near consistent and because the field on the card object is called `account`, the proposed naming here seems fine.

Thanks for the patch!
